type Course = {
  name: string;
  aliases: string[];
};

export const courses: Course[] = [
  { name: "The Joy of Computing", aliases: [] },
  { name: "Physical Computing and Robotics", aliases: [] },
  {
    name: "AP Computer Science Principles",
    aliases: ["CSP", "APCSP", "AP CSP"],
  },
  { name: "Web Design and Development", aliases: [] },
  { name: "AP Computer Science A", aliases: ["CSA", "APCSA", "AP CSA"] },
  { name: "Art I", aliases: ["Art 1"] },
  { name: "Art II", aliases: ["Art 2"] },
  { name: "Art III", aliases: ["Art 3"] },
  { name: "Art IV", aliases: ["Art 4"] },
  { name: "Digital Philosophy", aliases: [] },
  { name: "Digital Design", aliases: [] },
  { name: "AP Art 2-D Design Portfolio", aliases: [] },
  { name: "AP Art Drawing Portfolio", aliases: [] },
  { name: "Ceramics I", aliases: ["Ceramics 1"] },
  { name: "Ceramics II", aliases: ["Ceramics 2"] },
  { name: "Ceramics III", aliases: ["Ceramics 3"] },
  { name: "Ceramics IV", aliases: ["Ceramics 4"] },
  { name: "AP Studio Art 3-D Portfolio", aliases: [] },
  { name: "AP Art History", aliases: [] },
  { name: "Symphonic Band", aliases: [] },
  { name: "Jazz Band", aliases: [] },
  { name: "String Orchestra", aliases: [] },
  { name: "A Cappella", aliases: [] },
  { name: "A Cappella Advanced Choir", aliases: [] },
  { name: "Acting I", aliases: ["Acting 1"] },
  { name: "Acting II", aliases: ["Acting 2"] },
  { name: "Acting III", aliases: ["Acting 3"] },
  { name: "Acting IV", aliases: ["Acting 4"] },
  { name: "Directing and Production", aliases: ["Stage Production"] },
  { name: "Journalism", aliases: [] },
  { name: "Dance - Beginning", aliases: [] },
  { name: "Dance - Intermediate", aliases: [] },
  { name: "Dance - Advanced", aliases: [] },
  { name: "English 1-2", aliases: [] },
  { name: "English 3-4", aliases: [] },
  { name: "English 5-6", aliases: [] },
  { name: "English 5-6 Honors", aliases: ["Honors English"] },
  { name: "English 7-8", aliases: [] },
  { name: "AP English Literature", aliases: ["AP Literature"] },
  { name: "Creative Writing", aliases: [] },
  { name: "Public Speaking", aliases: [] },
  { name: "Film as Literature", aliases: [] },
  { name: "Integrated Math 1", aliases: ["IM 1", "IM1"] },
  { name: "Integrated Math 2", aliases: ["IM 2", "IM2"] },
  { name: "Integrated Math 3", aliases: ["IM 3", "IM3"] },
  { name: "Integrated Math 1/2A", aliases: ["IM 1/2A", "IM1/2A"] },
  { name: "Integrated Math 2B/3", aliases: ["IM 2B/3", "IM2B/3"] },
  { name: "Statistics", aliases: ["Stats"] },
  { name: "Honors Statistics", aliases: ["Honors Stats"] },
  { name: "Math Analysis", aliases: [] },
  { name: "Honors Math Analysis", aliases: ["HMA"] },
  { name: "AP Calculus AB", aliases: ["AP Calc AB"] },
  { name: "AP Calculus BC", aliases: ["AP Calc BC"] },
  { name: "Physical Education", aliases: ["PE"] },
  { name: "Weight Training", aliases: [] },
  { name: "Dance PE - Beginning", aliases: [] },
  { name: "Dance PE - Intermediate", aliases: [] },
  { name: "Dance PE - Advanced", aliases: [] },
  { name: "Biology And The Living Earth", aliases: [] },
  { name: "Chemistry in the Earth System", aliases: [] },
  { name: "Guitar Engineering", aliases: [] },
  { name: "Honors Chemistry", aliases: [] },
  { name: "Physics of the Universe", aliases: [] },
  { name: "Honors Physics of the Universe", aliases: [] },
  { name: "AP Biology", aliases: [] },
  { name: "AP Environmental Science", aliases: ["APES"] },
  { name: "AP Chemistry", aliases: [] },
  { name: "Anatomy and Physiology", aliases: [] },
  { name: "Entomology", aliases: [] },
  { name: "Marine Science", aliases: [] },
  { name: "World Cultures and Geography", aliases: [] },
  { name: "Modern World History", aliases: [] },
  { name: "U.S. History", aliases: [] },
  { name: "AP U.S. History", aliases: ["APUSH"] },
  { name: "Civics", aliases: [] },
  { name: "Economics", aliases: [] },
  { name: "Ethnic Studies", aliases: [] },
  { name: "Financial LIteracy and Personal Finance", aliases: [] },
  { name: "Law and Society", aliases: [] },
  { name: "Psychology", aliases: [] },
  { name: "Photojournalism", aliases: ["Yearbook"] },
  { name: "French 1", aliases: [] },
  { name: "French 2", aliases: [] },
  { name: "French 3", aliases: [] },
  { name: "French 4 Honors", aliases: ["Honors French"] },
  { name: "AP French", aliases: [] },
  { name: "Spanish 1", aliases: [] },
  { name: "Spanish 2", aliases: [] },
  { name: "Spanish 3", aliases: [] },
  { name: "Spanish 4 Honors", aliases: ["Honors Spanish"] },
  { name: "AP Spanish", aliases: [] },
  { name: "Chinese 1", aliases: [] },
  { name: "Chinese 2", aliases: [] },
  { name: "Chinese 3", aliases: [] },
  { name: "Chinese 4 Honors", aliases: ["Honors Chinese"] },
  { name: "AP Chinese", aliases: [] },
  { name: "ASB", aliases: [] },
  { name: "Health Science", aliases: [] },
  { name: "Learning Center", aliases: ["LC"] },
  {
    name: "Teacher/Office Assistant",
    aliases: ["Teaching Assistant", "TA", "Office Assistant"],
  },
  { name: "Free Period", aliases: [] },
];
